" Vim settings

syntax on

" Line number
set number

" Ctrl-E hotkey to enable CP1251
map <C-e> :e ++enc=cp1251<CR>

" End of line marker
set colorcolumn=80,120

" Unprintable symbols
set list
set listchars=eol:$,space:·,tab:>-,trail:~
" Ctrl-H hotkey to hide unprintable symbols
map <C-h> :set nolist nonumber<CR>
" Ctrl-S hotkey to show unprintable symbols
map <C-p> :set list number<CR>

" Tab
set tabstop=2
set softtabstop=0
set ts=2
set sw=2
set expandtab
set shiftwidth=4
"set smarttab

" Ctrl-T hotkey to enable tabs
map <C-t> :set noexpandtab<CR>

" Plugins will be downloaded under the specified directory.
call plug#begin('~/.vim/plugged')

" Declare the list of plugins.
Plug 'scrooloose/nerdtree'
Plug 'itchyny/lightline.vim'
Plug 'aklt/plantuml-syntax'

" List ends here. Plugins become visible to Vim after this call.
call plug#end()

" Plugins' settings
" Show panel with files
map <C-n> :NERDTreeToggle<CR>
set laststatus=2
