" Vim settings

syntax on

" Line number
set number

" Unprintable symbols
set list
set listchars=eol:$,space:·,tab:>-,trail:~

" Tab
set tabstop=2
set softtabstop=0
set expandtab ts=2 sw=2 ai
set shiftwidth=4
set smarttab

" Plugins will be downloaded under the specified directory.
call plug#begin('~/.vim/plugged')

" Declare the list of plugins.
Plug 'scrooloose/nerdtree'
Plug 'itchyny/lightline.vim'
Plug 'aklt/plantuml-syntax'

" List ends here. Plugins become visible to Vim after this call.
call plug#end()

" Plugins' settings
" Show panel with files
map <C-n> :NERDTreeToggle<CR>
set laststatus=2
